attack:
  train_domains:
    - label: clean
      type: clean
    - label: fgsm_rs
      type: fgsm
      eps: 0.0313725
      alpha: 0.0313725
      random_start: true
    - label: pgd_ce
      type: pgd
      eps: 0.0313725
      step_size: 0.007843
      num_steps: 7
      restarts: 1
      loss: ce
      random_start: true
    - label: pgd_dlr
      type: pgd
      eps: 0.0313725
      step_size: 0.007843
      num_steps: 7
      restarts: 1
      loss: dlr
      random_start: true
  val_suite:
    attacks:
      - label: clean
        type: clean
      - label: fgsm_rs
        type: fgsm
        eps: 0.0313725
        alpha: 0.0313725
        random_start: true
      - label: pgd_ce
        type: pgd
        eps: 0.0313725
        step_size: 0.007843
        num_steps: 7
        restarts: 1
        loss: ce
        random_start: true
      - label: pgd_dlr
        type: pgd
        eps: 0.0313725
        step_size: 0.007843
        num_steps: 7
        restarts: 1
        loss: dlr
        random_start: true
