attack:
  val_suite:
    attacks:
      - label: pgd_linf
        type: pgd
        norm: Linf
        eps: 0.0313725
        step_size: 0.007843
        num_steps: 10
        loss: ce
        random_start: true
      - label: cw_l2
        type: cw
        c: 1.0
        kappa: 0.0
        num_steps: 20
        lr: 0.01
  eval_suite:
    max_batches: 0
    attacks:
      - label: pgd_linf
        type: pgd
        norm: Linf
        eps: 0.0313725
        step_size: 0.007843
        num_steps: 10
        loss: ce
        random_start: true
      - label: cw_l2
        type: cw
        c: 1.0
        kappa: 0.0
        num_steps: 20
        lr: 0.01
