attack:
  train_domains:
    - name: pgd_linf
      type: pgd
      norm: Linf
      eps: 0.0313725
      step_size: 0.007843
      num_steps: 10
      loss: ce
      random_start: true
    - name: pgd_l2
      type: pgd
      norm: L2
      eps: 0.5
      step_size: 0.125
      num_steps: 10
      loss: ce
      random_start: true
